accounts:
  - name: rz
    coins: ["200000rzai", "200000000rzai"]
  - name: bob
    coins: ["100000rzai", "100000000rzai"]
validator:
  name: rz
  staked: "100000000rzai"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5000rzCosmos", "100000rzai"]
